<?php

use Illuminate\Database\Seeder;

class ProvinceCityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('province_cities')->truncate();
        DB::table('province_cities')->insert([
            
            ['id'=>'1', 'name' => '北京市', 'index'=> 1, 'parent' => 0, 'depth' => 0],
            ['id'=>'2', 'name' => '天津市', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'3', 'name' => '上海市', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'4', 'name' => '重庆市', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'5', 'name' => '河北省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'6', 'name' => '山西省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'7', 'name' => '台湾省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'8', 'name' => '辽宁省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'9', 'name' => '吉林省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'10', 'name' => '黑龙江省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'11', 'name' => '江苏省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'12', 'name' => '浙江省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'13', 'name' => '安徽省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'14', 'name' => '福建省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'15', 'name' => '江西省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'16', 'name' => '山东省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'17', 'name' => '河南省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'18', 'name' => '湖北省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'19', 'name' => '湖南省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'20', 'name' => '广东省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'21', 'name' => '甘肃省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'22', 'name' => '四川省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'23', 'name' => '贵州省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'24', 'name' => '海南省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'25', 'name' => '云南省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'26', 'name' => '青海省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'27', 'name' => '陕西省', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'28', 'name' => '广西壮族自治区', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'29', 'name' => '西藏自治区', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'30', 'name' => '宁夏回族自治区', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'31', 'name' => '新疆维吾尔自治区', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'32', 'name' => '内蒙古自治区', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'33', 'name' => '澳门特别行政区', 'index'=>1, 'parent'=>0, 'depth' => 0],
            ['id'=>'34', 'name' => '香港特别行政区', 'index'=>1, 'parent'=>0, 'depth' => 0],
        ]);

        DB::table('province_cities')->insert([
            ['index' => '1','parent' => '1','name' => '北京市', 'depth' => 1],
            ['index' => '1','parent' => '2','name' => '天津市', 'depth' => 1],
            ['index' => '1','parent' => '3','name' => '上海市', 'depth' => 1],
            ['index' => '1','parent' => '4','name' => '重庆市', 'depth' => 1],
            ['index' => '1','parent' => '5','name' => '石家庄市', 'depth' => 1],
            ['index' => '2','parent' => '5','name' => '唐山市', 'depth' => 1],
            ['index' => '3','parent' => '5','name' => '秦皇岛市', 'depth' => 1],
            ['index' => '4','parent' => '5','name' => '邯郸市', 'depth' => 1],
            ['index' => '5','parent' => '5','name' => '邢台市', 'depth' => 1],
            ['index' => '6','parent' => '5','name' => '保定市', 'depth' => 1],
            ['index' => '7','parent' => '5','name' => '张家口市', 'depth' => 1],
            ['index' => '8','parent' => '5','name' => '承德市', 'depth' => 1],
            ['index' => '9','parent' => '5','name' => '沧州市', 'depth' => 1],
            ['index' => '10','parent' => '5','name' => '廊坊市', 'depth' => 1],
            ['index' => '11','parent' => '5','name' => '衡水市', 'depth' => 1],
            ['index' => '1','parent' => '6','name' => '太原市', 'depth' => 1],
            ['index' => '2','parent' => '6','name' => '大同市', 'depth' => 1],
            ['index' => '3','parent' => '6','name' => '阳泉市', 'depth' => 1],
            ['index' => '4','parent' => '6','name' => '长治市', 'depth' => 1],
            ['index' => '5','parent' => '6','name' => '晋城市', 'depth' => 1],
            ['index' => '6','parent' => '6','name' => '朔州市', 'depth' => 1],
            ['index' => '7','parent' => '6','name' => '晋中市', 'depth' => 1],
            ['index' => '8','parent' => '6','name' => '运城市', 'depth' => 1],
            ['index' => '9','parent' => '6','name' => '忻州市', 'depth' => 1],
            ['index' => '10','parent' => '6','name' => '临汾市', 'depth' => 1],
            ['index' => '11','parent' => '6','name' => '吕梁市', 'depth' => 1],
            ['index' => '1','parent' => '7','name' => '台北市', 'depth' => 1],
            ['index' => '2','parent' => '7','name' => '高雄市', 'depth' => 1],
            ['index' => '3','parent' => '7','name' => '基隆市', 'depth' => 1],
            ['index' => '4','parent' => '7','name' => '台中市', 'depth' => 1],
            ['index' => '5','parent' => '7','name' => '台南市', 'depth' => 1],
            ['index' => '6','parent' => '7','name' => '新竹市', 'depth' => 1],
            ['index' => '7','parent' => '7','name' => '嘉义市', 'depth' => 1],
            ['index' => '8','parent' => '7','name' => '台北县', 'depth' => 1],
            ['index' => '9','parent' => '7','name' => '宜兰县', 'depth' => 1],
            ['index' => '10','parent' => '7','name' => '桃园县', 'depth' => 1],
            ['index' => '11','parent' => '7','name' => '新竹县', 'depth' => 1],
            ['index' => '12','parent' => '7','name' => '苗栗县', 'depth' => 1],
            ['index' => '13','parent' => '7','name' => '台中县', 'depth' => 1],
            ['index' => '14','parent' => '7','name' => '彰化县', 'depth' => 1],
            ['index' => '15','parent' => '7','name' => '南投县', 'depth' => 1],
            ['index' => '16','parent' => '7','name' => '云林县', 'depth' => 1],
            ['index' => '17','parent' => '7','name' => '嘉义县', 'depth' => 1],
            ['index' => '18','parent' => '7','name' => '台南县', 'depth' => 1],
            ['index' => '19','parent' => '7','name' => '高雄县', 'depth' => 1],
            ['index' => '20','parent' => '7','name' => '屏东县', 'depth' => 1],
            ['index' => '21','parent' => '7','name' => '澎湖县', 'depth' => 1],
            ['index' => '22','parent' => '7','name' => '台东县', 'depth' => 1],
            ['index' => '23','parent' => '7','name' => '花莲县', 'depth' => 1],
            ['index' => '1','parent' => '8','name' => '沈阳市', 'depth' => 1],
            ['index' => '2','parent' => '8','name' => '大连市', 'depth' => 1],
            ['index' => '3','parent' => '8','name' => '鞍山市', 'depth' => 1],
            ['index' => '4','parent' => '8','name' => '抚顺市', 'depth' => 1],
            ['index' => '5','parent' => '8','name' => '本溪市', 'depth' => 1],
            ['index' => '6','parent' => '8','name' => '丹东市', 'depth' => 1],
            ['index' => '7','parent' => '8','name' => '锦州市', 'depth' => 1],
            ['index' => '8','parent' => '8','name' => '营口市', 'depth' => 1],
            ['index' => '9','parent' => '8','name' => '阜新市', 'depth' => 1],
            ['index' => '10','parent' => '8','name' => '辽阳市', 'depth' => 1],
            ['index' => '11','parent' => '8','name' => '盘锦市', 'depth' => 1],
            ['index' => '12','parent' => '8','name' => '铁岭市', 'depth' => 1],
            ['index' => '13','parent' => '8','name' => '朝阳市', 'depth' => 1],
            ['index' => '14','parent' => '8','name' => '葫芦岛市', 'depth' => 1],
            ['index' => '1','parent' => '9','name' => '长春市', 'depth' => 1],
            ['index' => '2','parent' => '9','name' => '吉林市', 'depth' => 1],
            ['index' => '3','parent' => '9','name' => '四平市', 'depth' => 1],
            ['index' => '4','parent' => '9','name' => '辽源市', 'depth' => 1],
            ['index' => '5','parent' => '9','name' => '通化市', 'depth' => 1],
            ['index' => '6','parent' => '9','name' => '白山市', 'depth' => 1],
            ['index' => '7','parent' => '9','name' => '松原市', 'depth' => 1],
            ['index' => '8','parent' => '9','name' => '白城市', 'depth' => 1],
            ['index' => '9','parent' => '9','name' => '延边朝鲜族自治州', 'depth' => 1],
            ['index' => '1','parent' => '10','name' => '哈尔滨市', 'depth' => 1],
            ['index' => '2','parent' => '10','name' => '齐齐哈尔市', 'depth' => 1],
            ['index' => '3','parent' => '10','name' => '鹤岗市', 'depth' => 1],
            ['index' => '4','parent' => '10','name' => '双鸭山市', 'depth' => 1],
            ['index' => '5','parent' => '10','name' => '鸡西市', 'depth' => 1],
            ['index' => '6','parent' => '10','name' => '大庆市', 'depth' => 1],
            ['index' => '7','parent' => '10','name' => '伊春市', 'depth' => 1],
            ['index' => '8','parent' => '10','name' => '牡丹江市', 'depth' => 1],
            ['index' => '9','parent' => '10','name' => '佳木斯市', 'depth' => 1],
            ['index' => '10','parent' => '10','name' => '七台河市', 'depth' => 1],
            ['index' => '11','parent' => '10','name' => '黑河市', 'depth' => 1],
            ['index' => '12','parent' => '10','name' => '绥化市', 'depth' => 1],
            ['index' => '13','parent' => '10','name' => '大兴安岭地区', 'depth' => 1],
            ['index' => '1','parent' => '11','name' => '南京市', 'depth' => 1],
            ['index' => '2','parent' => '11','name' => '无锡市', 'depth' => 1],
            ['index' => '3','parent' => '11','name' => '徐州市', 'depth' => 1],
            ['index' => '4','parent' => '11','name' => '常州市', 'depth' => 1],
            ['index' => '5','parent' => '11','name' => '苏州市', 'depth' => 1],
            ['index' => '6','parent' => '11','name' => '南通市', 'depth' => 1],
            ['index' => '7','parent' => '11','name' => '连云港市', 'depth' => 1],
            ['index' => '8','parent' => '11','name' => '淮安市', 'depth' => 1],
            ['index' => '9','parent' => '11','name' => '盐城市', 'depth' => 1],
            ['index' => '10','parent' => '11','name' => '扬州市', 'depth' => 1],
            ['index' => '11','parent' => '11','name' => '镇江市', 'depth' => 1],
            ['index' => '12','parent' => '11','name' => '泰州市', 'depth' => 1],
            ['index' => '13','parent' => '11','name' => '宿迁市', 'depth' => 1],
            ['index' => '1','parent' => '12','name' => '杭州市', 'depth' => 1],
            ['index' => '2','parent' => '12','name' => '宁波市', 'depth' => 1],
            ['index' => '3','parent' => '12','name' => '温州市', 'depth' => 1],
            ['index' => '4','parent' => '12','name' => '嘉兴市', 'depth' => 1],
            ['index' => '5','parent' => '12','name' => '湖州市', 'depth' => 1],
            ['index' => '6','parent' => '12','name' => '绍兴市', 'depth' => 1],
            ['index' => '7','parent' => '12','name' => '金华市', 'depth' => 1],
            ['index' => '8','parent' => '12','name' => '衢州市', 'depth' => 1],
            ['index' => '9','parent' => '12','name' => '舟山市', 'depth' => 1],
            ['index' => '10','parent' => '12','name' => '台州市', 'depth' => 1],
            ['index' => '11','parent' => '12','name' => '丽水市', 'depth' => 1],
            ['index' => '1','parent' => '13','name' => '合肥市', 'depth' => 1],
            ['index' => '2','parent' => '13','name' => '芜湖市', 'depth' => 1],
            ['index' => '3','parent' => '13','name' => '蚌埠市', 'depth' => 1],
            ['index' => '4','parent' => '13','name' => '淮南市', 'depth' => 1],
            ['index' => '5','parent' => '13','name' => '马鞍山市', 'depth' => 1],
            ['index' => '6','parent' => '13','name' => '淮北市', 'depth' => 1],
            ['index' => '7','parent' => '13','name' => '铜陵市', 'depth' => 1],
            ['index' => '8','parent' => '13','name' => '安庆市', 'depth' => 1],
            ['index' => '9','parent' => '13','name' => '黄山市', 'depth' => 1],
            ['index' => '10','parent' => '13','name' => '滁州市', 'depth' => 1],
            ['index' => '11','parent' => '13','name' => '阜阳市', 'depth' => 1],
            ['index' => '12','parent' => '13','name' => '宿州市', 'depth' => 1],
            ['index' => '13','parent' => '13','name' => '巢湖市', 'depth' => 1],
            ['index' => '14','parent' => '13','name' => '六安市', 'depth' => 1],
            ['index' => '15','parent' => '13','name' => '亳州市', 'depth' => 1],
            ['index' => '16','parent' => '13','name' => '池州市', 'depth' => 1],
            ['index' => '17','parent' => '13','name' => '宣城市', 'depth' => 1],
            ['index' => '1','parent' => '14','name' => '福州市', 'depth' => 1],
            ['index' => '2','parent' => '14','name' => '厦门市', 'depth' => 1],
            ['index' => '3','parent' => '14','name' => '莆田市', 'depth' => 1],
            ['index' => '4','parent' => '14','name' => '三明市', 'depth' => 1],
            ['index' => '5','parent' => '14','name' => '泉州市', 'depth' => 1],
            ['index' => '6','parent' => '14','name' => '漳州市', 'depth' => 1],
            ['index' => '7','parent' => '14','name' => '南平市', 'depth' => 1],
            ['index' => '8','parent' => '14','name' => '龙岩市', 'depth' => 1],
            ['index' => '9','parent' => '14','name' => '宁德市', 'depth' => 1],
            ['index' => '1','parent' => '15','name' => '南昌市', 'depth' => 1],
            ['index' => '2','parent' => '15','name' => '景德镇市', 'depth' => 1],
            ['index' => '3','parent' => '15','name' => '萍乡市', 'depth' => 1],
            ['index' => '4','parent' => '15','name' => '九江市', 'depth' => 1],
            ['index' => '5','parent' => '15','name' => '新余市', 'depth' => 1],
            ['index' => '6','parent' => '15','name' => '鹰潭市', 'depth' => 1],
            ['index' => '7','parent' => '15','name' => '赣州市', 'depth' => 1],
            ['index' => '8','parent' => '15','name' => '吉安市', 'depth' => 1],
            ['index' => '9','parent' => '15','name' => '宜春市', 'depth' => 1],
            ['index' => '10','parent' => '15','name' => '抚州市', 'depth' => 1],
            ['index' => '11','parent' => '15','name' => '上饶市', 'depth' => 1],
            ['index' => '1','parent' => '16','name' => '济南市', 'depth' => 1],
            ['index' => '2','parent' => '16','name' => '青岛市', 'depth' => 1],
            ['index' => '3','parent' => '16','name' => '淄博市', 'depth' => 1],
            ['index' => '4','parent' => '16','name' => '枣庄市', 'depth' => 1],
            ['index' => '5','parent' => '16','name' => '东营市', 'depth' => 1],
            ['index' => '6','parent' => '16','name' => '烟台市', 'depth' => 1],
            ['index' => '7','parent' => '16','name' => '潍坊市', 'depth' => 1],
            ['index' => '8','parent' => '16','name' => '济宁市', 'depth' => 1],
            ['index' => '9','parent' => '16','name' => '泰安市', 'depth' => 1],
            ['index' => '10','parent' => '16','name' => '威海市', 'depth' => 1],
            ['index' => '11','parent' => '16','name' => '日照市', 'depth' => 1],
            ['index' => '12','parent' => '16','name' => '莱芜市', 'depth' => 1],
            ['index' => '13','parent' => '16','name' => '临沂市', 'depth' => 1],
            ['index' => '14','parent' => '16','name' => '德州市', 'depth' => 1],
            ['index' => '15','parent' => '16','name' => '聊城市', 'depth' => 1],
            ['index' => '16','parent' => '16','name' => '滨州市', 'depth' => 1],
            ['index' => '17','parent' => '16','name' => '菏泽市', 'depth' => 1],
            ['index' => '1','parent' => '17','name' => '郑州市', 'depth' => 1],
            ['index' => '2','parent' => '17','name' => '开封市', 'depth' => 1],
            ['index' => '3','parent' => '17','name' => '洛阳市', 'depth' => 1],
            ['index' => '4','parent' => '17','name' => '平顶山市', 'depth' => 1],
            ['index' => '5','parent' => '17','name' => '安阳市', 'depth' => 1],
            ['index' => '6','parent' => '17','name' => '鹤壁市', 'depth' => 1],
            ['index' => '7','parent' => '17','name' => '新乡市', 'depth' => 1],
            ['index' => '8','parent' => '17','name' => '焦作市', 'depth' => 1],
            ['index' => '9','parent' => '17','name' => '濮阳市', 'depth' => 1],
            ['index' => '10','parent' => '17','name' => '许昌市', 'depth' => 1],
            ['index' => '11','parent' => '17','name' => '漯河市', 'depth' => 1],
            ['index' => '12','parent' => '17','name' => '三门峡市', 'depth' => 1],
            ['index' => '13','parent' => '17','name' => '南阳市', 'depth' => 1],
            ['index' => '14','parent' => '17','name' => '商丘市', 'depth' => 1],
            ['index' => '15','parent' => '17','name' => '信阳市', 'depth' => 1],
            ['index' => '16','parent' => '17','name' => '周口市', 'depth' => 1],
            ['index' => '17','parent' => '17','name' => '驻马店市', 'depth' => 1],
            ['index' => '18','parent' => '17','name' => '济源市', 'depth' => 1],
            ['index' => '1','parent' => '18','name' => '武汉市', 'depth' => 1],
            ['index' => '2','parent' => '18','name' => '黄石市', 'depth' => 1],
            ['index' => '3','parent' => '18','name' => '十堰市', 'depth' => 1],
            ['index' => '4','parent' => '18','name' => '荆州市', 'depth' => 1],
            ['index' => '5','parent' => '18','name' => '宜昌市', 'depth' => 1],
            ['index' => '6','parent' => '18','name' => '襄樊市', 'depth' => 1],
            ['index' => '7','parent' => '18','name' => '鄂州市', 'depth' => 1],
            ['index' => '8','parent' => '18','name' => '荆门市', 'depth' => 1],
            ['index' => '9','parent' => '18','name' => '孝感市', 'depth' => 1],
            ['index' => '10','parent' => '18','name' => '黄冈市', 'depth' => 1],
            ['index' => '11','parent' => '18','name' => '咸宁市', 'depth' => 1],
            ['index' => '12','parent' => '18','name' => '随州市', 'depth' => 1],
            ['index' => '13','parent' => '18','name' => '仙桃市', 'depth' => 1],
            ['index' => '14','parent' => '18','name' => '天门市', 'depth' => 1],
            ['index' => '15','parent' => '18','name' => '潜江市', 'depth' => 1],
            ['index' => '16','parent' => '18','name' => '神农架林区', 'depth' => 1],
            ['index' => '17','parent' => '18','name' => '恩施土家族苗族自治州', 'depth' => 1],
            ['index' => '1','parent' => '19','name' => '长沙市', 'depth' => 1],
            ['index' => '2','parent' => '19','name' => '株洲市', 'depth' => 1],
            ['index' => '3','parent' => '19','name' => '湘潭市', 'depth' => 1],
            ['index' => '4','parent' => '19','name' => '衡阳市', 'depth' => 1],
            ['index' => '5','parent' => '19','name' => '邵阳市', 'depth' => 1],
            ['index' => '6','parent' => '19','name' => '岳阳市', 'depth' => 1],
            ['index' => '7','parent' => '19','name' => '常德市', 'depth' => 1],
            ['index' => '8','parent' => '19','name' => '张家界市', 'depth' => 1],
            ['index' => '9','parent' => '19','name' => '益阳市', 'depth' => 1],
            ['index' => '10','parent' => '19','name' => '郴州市', 'depth' => 1],
            ['index' => '11','parent' => '19','name' => '永州市', 'depth' => 1],
            ['index' => '12','parent' => '19','name' => '怀化市', 'depth' => 1],
            ['index' => '13','parent' => '19','name' => '娄底市', 'depth' => 1],
            ['index' => '14','parent' => '19','name' => '湘西土家族苗族自治州', 'depth' => 1],
            ['index' => '1','parent' => '20','name' => '广州市', 'depth' => 1],
            ['index' => '2','parent' => '20','name' => '深圳市', 'depth' => 1],
            ['index' => '3','parent' => '20','name' => '珠海市', 'depth' => 1],
            ['index' => '4','parent' => '20','name' => '汕头市', 'depth' => 1],
            ['index' => '5','parent' => '20','name' => '韶关市', 'depth' => 1],
            ['index' => '6','parent' => '20','name' => '佛山市', 'depth' => 1],
            ['index' => '7','parent' => '20','name' => '江门市', 'depth' => 1],
            ['index' => '8','parent' => '20','name' => '湛江市', 'depth' => 1],
            ['index' => '9','parent' => '20','name' => '茂名市', 'depth' => 1],
            ['index' => '10','parent' => '20','name' => '肇庆市', 'depth' => 1],
            ['index' => '11','parent' => '20','name' => '惠州市', 'depth' => 1],
            ['index' => '12','parent' => '20','name' => '梅州市', 'depth' => 1],
            ['index' => '13','parent' => '20','name' => '汕尾市', 'depth' => 1],
            ['index' => '14','parent' => '20','name' => '河源市', 'depth' => 1],
            ['index' => '15','parent' => '20','name' => '阳江市', 'depth' => 1],
            ['index' => '16','parent' => '20','name' => '清远市', 'depth' => 1],
            ['index' => '17','parent' => '20','name' => '东莞市', 'depth' => 1],
            ['index' => '18','parent' => '20','name' => '中山市', 'depth' => 1],
            ['index' => '19','parent' => '20','name' => '潮州市', 'depth' => 1],
            ['index' => '20','parent' => '20','name' => '揭阳市', 'depth' => 1],
            ['index' => '21','parent' => '20','name' => '云浮市', 'depth' => 1],
            ['index' => '1','parent' => '21','name' => '兰州市', 'depth' => 1],
            ['index' => '2','parent' => '21','name' => '金昌市', 'depth' => 1],
            ['index' => '3','parent' => '21','name' => '白银市', 'depth' => 1],
            ['index' => '4','parent' => '21','name' => '天水市', 'depth' => 1],
            ['index' => '5','parent' => '21','name' => '嘉峪关市', 'depth' => 1],
            ['index' => '6','parent' => '21','name' => '武威市', 'depth' => 1],
            ['index' => '7','parent' => '21','name' => '张掖市', 'depth' => 1],
            ['index' => '8','parent' => '21','name' => '平凉市', 'depth' => 1],
            ['index' => '9','parent' => '21','name' => '酒泉市', 'depth' => 1],
            ['index' => '10','parent' => '21','name' => '庆阳市', 'depth' => 1],
            ['index' => '11','parent' => '21','name' => '定西市', 'depth' => 1],
            ['index' => '12','parent' => '21','name' => '陇南市', 'depth' => 1],
            ['index' => '13','parent' => '21','name' => '临夏回族自治州', 'depth' => 1],
            ['index' => '14','parent' => '21','name' => '甘南藏族自治州', 'depth' => 1],
            ['index' => '1','parent' => '22','name' => '成都市', 'depth' => 1],
            ['index' => '2','parent' => '22','name' => '自贡市', 'depth' => 1],
            ['index' => '3','parent' => '22','name' => '攀枝花市', 'depth' => 1],
            ['index' => '4','parent' => '22','name' => '泸州市', 'depth' => 1],
            ['index' => '5','parent' => '22','name' => '德阳市', 'depth' => 1],
            ['index' => '6','parent' => '22','name' => '绵阳市', 'depth' => 1],
            ['index' => '7','parent' => '22','name' => '广元市', 'depth' => 1],
            ['index' => '8','parent' => '22','name' => '遂宁市', 'depth' => 1],
            ['index' => '9','parent' => '22','name' => '内江市', 'depth' => 1],
            ['index' => '10','parent' => '22','name' => '乐山市', 'depth' => 1],
            ['index' => '11','parent' => '22','name' => '南充市', 'depth' => 1],
            ['index' => '12','parent' => '22','name' => '眉山市', 'depth' => 1],
            ['index' => '13','parent' => '22','name' => '宜宾市', 'depth' => 1],
            ['index' => '14','parent' => '22','name' => '广安市', 'depth' => 1],
            ['index' => '15','parent' => '22','name' => '达州市', 'depth' => 1],
            ['index' => '16','parent' => '22','name' => '雅安市', 'depth' => 1],
            ['index' => '17','parent' => '22','name' => '巴中市', 'depth' => 1],
            ['index' => '18','parent' => '22','name' => '资阳市', 'depth' => 1],
            ['index' => '19','parent' => '22','name' => '阿坝藏族羌族自治州', 'depth' => 1],
            ['index' => '20','parent' => '22','name' => '甘孜藏族自治州', 'depth' => 1],
            ['index' => '21','parent' => '22','name' => '凉山彝族自治州', 'depth' => 1],
            ['index' => '1','parent' => '23','name' => '贵阳市', 'depth' => 1],
            ['index' => '2','parent' => '23','name' => '六盘水市', 'depth' => 1],
            ['index' => '3','parent' => '23','name' => '遵义市', 'depth' => 1],
            ['index' => '4','parent' => '23','name' => '安顺市', 'depth' => 1],
            ['index' => '5','parent' => '23','name' => '铜仁地区', 'depth' => 1],
            ['index' => '6','parent' => '23','name' => '毕节地区', 'depth' => 1],
            ['index' => '7','parent' => '23','name' => '黔西南布依族苗族自治州', 'depth' => 1],
            ['index' => '8','parent' => '23','name' => '黔东南苗族侗族自治州', 'depth' => 1],
            ['index' => '9','parent' => '23','name' => '黔南布依族苗族自治州', 'depth' => 1],
            ['index' => '1','parent' => '24','name' => '海口市', 'depth' => 1],
            ['index' => '2','parent' => '24','name' => '三亚市', 'depth' => 1],
            ['index' => '3','parent' => '24','name' => '五指山市', 'depth' => 1],
            ['index' => '4','parent' => '24','name' => '琼海市', 'depth' => 1],
            ['index' => '5','parent' => '24','name' => '儋州市', 'depth' => 1],
            ['index' => '6','parent' => '24','name' => '文昌市', 'depth' => 1],
            ['index' => '7','parent' => '24','name' => '万宁市', 'depth' => 1],
            ['index' => '8','parent' => '24','name' => '东方市', 'depth' => 1],
            ['index' => '9','parent' => '24','name' => '澄迈县', 'depth' => 1],
            ['index' => '10','parent' => '24','name' => '定安县', 'depth' => 1],
            ['index' => '11','parent' => '24','name' => '屯昌县', 'depth' => 1],
            ['index' => '12','parent' => '24','name' => '临高县', 'depth' => 1],
            ['index' => '13','parent' => '24','name' => '白沙黎族自治县', 'depth' => 1],
            ['index' => '14','parent' => '24','name' => '昌江黎族自治县', 'depth' => 1],
            ['index' => '15','parent' => '24','name' => '乐东黎族自治县', 'depth' => 1],
            ['index' => '16','parent' => '24','name' => '陵水黎族自治县', 'depth' => 1],
            ['index' => '17','parent' => '24','name' => '保亭黎族苗族自治县', 'depth' => 1],
            ['index' => '18','parent' => '24','name' => '琼中黎族苗族自治县', 'depth' => 1],
            ['index' => '1','parent' => '25','name' => '昆明市', 'depth' => 1],
            ['index' => '2','parent' => '25','name' => '曲靖市', 'depth' => 1],
            ['index' => '3','parent' => '25','name' => '玉溪市', 'depth' => 1],
            ['index' => '4','parent' => '25','name' => '保山市', 'depth' => 1],
            ['index' => '5','parent' => '25','name' => '昭通市', 'depth' => 1],
            ['index' => '6','parent' => '25','name' => '丽江市', 'depth' => 1],
            ['index' => '7','parent' => '25','name' => '思茅市', 'depth' => 1],
            ['index' => '8','parent' => '25','name' => '临沧市', 'depth' => 1],
            ['index' => '9','parent' => '25','name' => '文山壮族苗族自治州', 'depth' => 1],
            ['index' => '10','parent' => '25','name' => '红河哈尼族彝族自治州', 'depth' => 1],
            ['index' => '11','parent' => '25','name' => '西双版纳傣族自治州', 'depth' => 1],
            ['index' => '12','parent' => '25','name' => '楚雄彝族自治州', 'depth' => 1],
            ['index' => '13','parent' => '25','name' => '大理白族自治州', 'depth' => 1],
            ['index' => '14','parent' => '25','name' => '德宏傣族景颇族自治州', 'depth' => 1],
            ['index' => '15','parent' => '25','name' => '怒江傈傈族自治州', 'depth' => 1],
            ['index' => '16','parent' => '25','name' => '迪庆藏族自治州', 'depth' => 1],
            ['index' => '1','parent' => '26','name' => '西宁市', 'depth' => 1],
            ['index' => '2','parent' => '26','name' => '海东地区', 'depth' => 1],
            ['index' => '3','parent' => '26','name' => '海北藏族自治州', 'depth' => 1],
            ['index' => '4','parent' => '26','name' => '黄南藏族自治州', 'depth' => 1],
            ['index' => '5','parent' => '26','name' => '海南藏族自治州', 'depth' => 1],
            ['index' => '6','parent' => '26','name' => '果洛藏族自治州', 'depth' => 1],
            ['index' => '7','parent' => '26','name' => '玉树藏族自治州', 'depth' => 1],
            ['index' => '8','parent' => '26','name' => '海西蒙古族藏族自治州', 'depth' => 1],
            ['index' => '1','parent' => '27','name' => '西安市', 'depth' => 1],
            ['index' => '2','parent' => '27','name' => '铜川市', 'depth' => 1],
            ['index' => '3','parent' => '27','name' => '宝鸡市', 'depth' => 1],
            ['index' => '4','parent' => '27','name' => '咸阳市', 'depth' => 1],
            ['index' => '5','parent' => '27','name' => '渭南市', 'depth' => 1],
            ['index' => '6','parent' => '27','name' => '延安市', 'depth' => 1],
            ['index' => '7','parent' => '27','name' => '汉中市', 'depth' => 1],
            ['index' => '8','parent' => '27','name' => '榆林市', 'depth' => 1],
            ['index' => '9','parent' => '27','name' => '安康市', 'depth' => 1],
            ['index' => '10','parent' => '27','name' => '商洛市', 'depth' => 1],
            ['index' => '1','parent' => '28','name' => '南宁市', 'depth' => 1],
            ['index' => '2','parent' => '28','name' => '柳州市', 'depth' => 1],
            ['index' => '3','parent' => '28','name' => '桂林市', 'depth' => 1],
            ['index' => '4','parent' => '28','name' => '梧州市', 'depth' => 1],
            ['index' => '5','parent' => '28','name' => '北海市', 'depth' => 1],
            ['index' => '6','parent' => '28','name' => '防城港市', 'depth' => 1],
            ['index' => '7','parent' => '28','name' => '钦州市', 'depth' => 1],
            ['index' => '8','parent' => '28','name' => '贵港市', 'depth' => 1],
            ['index' => '9','parent' => '28','name' => '玉林市', 'depth' => 1],
            ['index' => '10','parent' => '28','name' => '百色市', 'depth' => 1],
            ['index' => '11','parent' => '28','name' => '贺州市', 'depth' => 1],
            ['index' => '12','parent' => '28','name' => '河池市', 'depth' => 1],
            ['index' => '13','parent' => '28','name' => '来宾市', 'depth' => 1],
            ['index' => '14','parent' => '28','name' => '崇左市', 'depth' => 1],
            ['index' => '1','parent' => '29','name' => '拉萨市', 'depth' => 1],
            ['index' => '2','parent' => '29','name' => '那曲地区', 'depth' => 1],
            ['index' => '3','parent' => '29','name' => '昌都地区', 'depth' => 1],
            ['index' => '4','parent' => '29','name' => '山南地区', 'depth' => 1],
            ['index' => '5','parent' => '29','name' => '日喀则地区', 'depth' => 1],
            ['index' => '6','parent' => '29','name' => '阿里地区', 'depth' => 1],
            ['index' => '7','parent' => '29','name' => '林芝地区', 'depth' => 1],
            ['index' => '1','parent' => '30','name' => '银川市', 'depth' => 1],
            ['index' => '2','parent' => '30','name' => '石嘴山市', 'depth' => 1],
            ['index' => '3','parent' => '30','name' => '吴忠市', 'depth' => 1],
            ['index' => '4','parent' => '30','name' => '固原市', 'depth' => 1],
            ['index' => '5','parent' => '30','name' => '中卫市', 'depth' => 1],
            ['index' => '1','parent' => '31','name' => '乌鲁木齐市', 'depth' => 1],
            ['index' => '2','parent' => '31','name' => '克拉玛依市', 'depth' => 1],
            ['index' => '3','parent' => '31','name' => '石河子市', 'depth' => 1],
            ['index' => '4','parent' => '31','name' => '阿拉尔市', 'depth' => 1],
            ['index' => '5','parent' => '31','name' => '图木舒克市', 'depth' => 1],
            ['index' => '6','parent' => '31','name' => '五家渠市', 'depth' => 1],
            ['index' => '7','parent' => '31','name' => '吐鲁番市', 'depth' => 1],
            ['index' => '8','parent' => '31','name' => '阿克苏市', 'depth' => 1],
            ['index' => '9','parent' => '31','name' => '喀什市', 'depth' => 1],
            ['index' => '10','parent' => '31','name' => '哈密市', 'depth' => 1],
            ['index' => '11','parent' => '31','name' => '和田市', 'depth' => 1],
            ['index' => '12','parent' => '31','name' => '阿图什市', 'depth' => 1],
            ['index' => '13','parent' => '31','name' => '库尔勒市', 'depth' => 1],
            ['index' => '14','parent' => '31', 'name' => '昌吉市', 'depth' => 1],
            ['index' => '15','parent' => '31','name' => '阜康市', 'depth' => 1],
            ['index' => '16','parent' => '31','name' => '米泉市', 'depth' => 1],
            ['index' => '17','parent' => '31','name' => '博乐市', 'depth' => 1],
            ['index' => '18','parent' => '31','name' => '伊宁市', 'depth' => 1],
            ['index' => '19','parent' => '31','name' => '奎屯市', 'depth' => 1],
            ['index' => '20','parent' => '31','name' => '塔城市', 'depth' => 1],
            ['index' => '21','parent' => '31','name' => '乌苏市', 'depth' => 1],
            ['index' => '22','parent' => '31','name' => '阿勒泰市', 'depth' => 1],
            ['index' => '1','parent' => '32','name' => '呼和浩特市', 'depth' => 1],
            ['index' => '2','parent' => '32','name' => '包头市', 'depth' => 1],
            ['index' => '3','parent' => '32','name' => '乌海市', 'depth' => 1],
            ['index' => '4','parent' => '32','name' => '赤峰市', 'depth' => 1],
            ['index' => '5','parent' => '32','name' => '通辽市', 'depth' => 1],
            ['index' => '6','parent' => '32','name' => '鄂尔多斯市', 'depth' => 1],
            ['index' => '7','parent' => '32','name' => '呼伦贝尔市', 'depth' => 1],
            ['index' => '8','parent' => '32','name' => '巴彦淖尔市', 'depth' => 1],
            ['index' => '9','parent' => '32','name' => '乌兰察布市', 'depth' => 1],
            ['index' => '10','parent' => '32','name' => '锡林郭勒盟', 'depth' => 1],
            ['index' => '11','parent' => '32','name' => '兴安盟', 'depth' => 1],
            ['index' => '12','parent' => '32','name' => '阿拉善盟', 'depth' => 1],
            ['index' => '1','parent' => '33','name' => '澳门特别行政区', 'depth' => 1],
            ['index' => '1','parent' => '34','name' => '香港特别行政区', 'depth' => 1],
        ]);
    }
}
