<?php

namespace App\Models;

use App\Models\Observer\RechargeGroupObserver;
use Illuminate\Database\Eloquent\Model;

class RechargeGroup extends Model
{
    //
    protected $table = 'recharge_groups';
    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::observe(RechargeGroupObserver::class);
    }

    //scope
    public function scopeByDefault($query)
    {
        return $query->where('is_default', 1);
    }

    public function scopeByBuz($query)
    {
        return $query->where('classify', 0);
    }

}
